pipeline {
    agent any
    
    tools {
        jdk 'jdk21'
        maven 'maven3'
    }
    
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        // CHANGE THIS to your DockerHub Username
        DOCKERHUB_USERNAME = 'ryansaad85' 
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Clone the main repository where the project lives
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/ryansaad/DevOps-Projects.git'
            }
        }
        
        stage('Compile & Build') {
            steps {
                // Enter the specific project directory
                dir('DevOps-Project-32/JavaApp-CICD') {
                    sh 'mvn clean package'
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('DevOps-Project-32/JavaApp-CICD') {
                    withSonarQubeEnv('sonar-server') {
                        sh '''$SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.projectKey=Petclinic \
                        -Dsonar.projectName=Petclinic \
                        -Dsonar.java.binaries=target'''
                    }
                }
            }
        }
        
        // stage('OWASP Dependency Check') {
        //     steps {
        //         dir('DevOps-Project-32/JavaApp-CICD') {
        //             dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'dependency-check'
        //         }
        //     }
        // }
        
        stage('Docker Build & Push') {
            steps {
                dir('DevOps-Project-32/JavaApp-CICD') {
                    script {
                        docker.withRegistry('', 'docker') {
                            // We are now inside the folder, so we can build from current dir (.)
                            def dockerImage = docker.build("${env.DOCKERHUB_USERNAME}/petclinic:latest")
                            dockerImage.push()
                        }
                    }
                }
            }
        }
        
        stage('Deploy to Tomcat') {
            steps {
                // We use "${WORKSPACE}" to force the full absolute path
                // Note: We MUST use double quotes " " for the variable to work
                sh "sudo cp ${WORKSPACE}/DevOps-Project-32/JavaApp-CICD/target/petclinic.war /opt/apache-tomcat-9.0.65/webapps/"
            }
        }
    }
}