version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
  pre_build:
    commands:
      # Navigate to correct folder
      - cd DevOps-Project-23/Swiggy_clone
      - echo "Current directory:"
      - pwd 
      
      - echo "Installing dependencies..."
      # INSTALL LATEST TRIVY (Fixes Rate Limit Error)
      - sudo apt-get install wget apt-transport-https gnupg lsb-release -y
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
      - echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
      - sudo apt-get update
      - sudo apt-get install trivy -y
      
      # Run Trivy File Scan
      - echo "Performing Trivy file scan..."
      - trivy filesystem --exit-code 0 --no-progress . >> trivyfilescan.txt
      
      # Install Sonar Scanner
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"

  build:
    commands:
      # We are already in the correct folder
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - export DOCKER_USERNAME_LOWER=$(echo "$DOCKER_REGISTRY_USERNAME" | tr '[:upper:]' '[:lower:]')
      - docker push "$DOCKER_REGISTRY_USERNAME/swiggy:latest"

  post_build:
    commands:
      - echo "Performing Trivy image scan..."
      - trivy image "$DOCKER_REGISTRY_USERNAME/swiggy:latest" >> trivyimage.txt
      - echo "Running SonarQube analysis..."
      # REPLACE THE IP BELOW WITH YOUR SONAR SERVER PUBLIC IP
      - sonar-scanner -Dsonar.projectKey=swiggy -Dsonar.sources=. -Dsonar.host.url=http://44.210.131.159:9000/ -Dsonar.login=$SONAR_TOKEN
      - echo "Build completed successfully!"

artifacts:
  files:
    - appspec.yaml
  base-directory: DevOps-Project-23/Swiggy_clone