pipeline {
    agent any
    
    tools {
        jdk "jdk17"     // Matches your Jenkins Tool configuration
        maven "maven3"  // Matches your Jenkins Tool configuration
    }
    
    environment {
        // Your DockerHub Image Name
        DOCKER_IMAGE = "ryansaad85/blogging-app"
    }
    
    stages {
        stage('Git Checkout') {
            steps {
                // Jenkins automatically checks out source code in "Pipeline from SCM"
                checkout scm
            }
        }
        
        stage('Compile') {
            steps {
                sh "mvn compile"
            }
        }
        
        stage('Trivy FS') {
            steps {
                sh "trivy fs . --format table -o fs.html"
            }
        }
        
        stage('Build') {
            steps {
                sh "mvn package"
            }
        }
        
        stage('Docker Build & Tag') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/') {
                        sh "docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ."
                        sh "docker tag ${DOCKER_IMAGE}:${BUILD_NUMBER} ${DOCKER_IMAGE}:latest"
                    }
                }
            }
        }
        
        stage('Docker Push Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/') {
                        sh "docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}"
                        sh "docker push ${DOCKER_IMAGE}:latest"
                    }
                }
            }
        }
    }
}