def registry = 'https://trialrpjcof.jfrog.io'
def imageName = 'satishk.jfrog.io/satish-docker-local/sample_app'
def version   = '2.1.2'
pipeline {
    agent {
        node {
            label 'maven'
        }
    }
environment {
    PATH = "/opt/apache-maven-3.9.4/bin:$PATH"
}
    stages {
        stage("build"){
            steps {
                dir('DevOps-Project-06') {
                 echo "----------- build started ----------"
                sh 'mvn clean install -Dmaven.repo.local=jarstaging -Dmaven.test.skip=true'
                 echo "----------- build complted ----------"
                }
            }
        }
        stage("test"){
            steps{
                dir('DevOps-Project-06') {
                    echo "----------- unit test started ----------"
                    sh 'mvn surefire-report:report'
                     echo "----------- unit test Complted ----------"
                }
            }
        }

        stage('SonarQube analysis') {
        environment {
          scannerHome = tool 'sonarqube-scanner'
        }
            steps{
                dir('DevOps-Project-06') {
            withSonarQubeEnv('sonarqube-server') { // If you have configured more than one global server connection, you can specify its name
              sh "${scannerHome}/bin/sonar-scanner"
            }
            }
            }
        }
        // stage("Quality Gate"){
        // steps {
        //     script {
        //         timeout(time: 1, unit: 'HOURS') {
        //             def qg = waitForQualityGate()
        //             if (qg.status != 'OK' && qg.status != 'NONE') {
        //                 error "Pipeline aborted due to quality gate failure: ${qg.status}"
        //                 }
        //             }
        //         }    
        //     }
        // }
         stage("Jar Publish") {
            steps {
                script {
                    echo '<--------------- Jar Publish Started --------------->'
                    // This connects using the URL and Credential ID directly
                    def server = Artifactory.newServer url: registry + "/artifactory", credentialsId: "jfrog_cred"
            
                    def properties = "buildid=${env.BUILD_ID},commitid=${GIT_COMMIT}";
            
                    def uploadSpec = """{
                "files": [
                  {
                    
                    "pattern": "DevOps-Project-06/jarstaging/(com/satish/demo-workshop/.*)", 
                    "target": "libs-release-local/{1}",
                    "flat": "false",
                    "props" : "${properties}",
                    "exclusions": [ "*.sha1", "*.md5"]
                  }
                ]
            }"""
            
                    // ⚠️ Verify "libs-release-local" matches the exact name of the repo you created in JFrog!
            
                def buildInfo = server.upload(uploadSpec)
                buildInfo.env.collect()
                server.publishBuildInfo(buildInfo)
                echo '<--------------- Jar Publish Ended --------------->'  
            }
        }   
    }


    stage(" Docker Build ") {
      steps {
        script {
           echo '<--------------- Docker Build Started --------------->'
           app = docker.build(imageName+":"+version)
           echo '<--------------- Docker Build Ends --------------->'
        }
      }
    }

            stage (" Docker Publish "){
        steps {
            script {
               echo '<--------------- Docker Publish Started --------------->'  
                docker.withRegistry(registry, 'jfrog_cred'){
                    app.push()
                }    
               echo '<--------------- Docker Publish Ended --------------->'  
            }
        }
    }

    // stage (" Deploy "){
    //     steps {
    //         script {
    //            sh './deploy.sh'  
    //         }
    //     }
    // }

stage(" Deploy ") {
       steps {
         script {
            echo '<--------------- Helm Deploy Started --------------->'
            sh 'helm install sample-app sample-app-1.0.1'
            echo '<--------------- Helm deploy Ends --------------->'
         }
       }
}  
}
}


